---
- hosts: localhost
  vars:
    vcenter_server: "168.1.107.242"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "RH[}3y5p"
    
  tasks:
    - name: Exit ESXi "{{ ansible_play_hosts }}" from maintenance mode
      vmware_maintenancemode:
        validate_certs: no
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_hostname }}"
        state: absent
      register: host_result

    - name: Assert that host {{ ansible_play_hosts }} is in maintenance mode
      assert:
        that:
          - "host_result.changed"
