---
- hosts: all
  tasks:
    - include_vars: "update_esxi_defaults.yaml"
    
    - name: Create temp directory
      file:
        path: "{{ '/vmfs/volumes/datastore*/' + temp_dir|default(default_temp_dir) }}"
        state: directory
        mode: 0755
      

