---
- hosts: all
  vars:
    add_slash: "/"
    
  tasks: 
    - include_vars: "update_esxi_defaults.yaml"
  
    - name: list storahe file systems available on ESXi host and grep only the local datastorage
      shell: "esxcli storage filesystem list | grep datastore"
      register: out_pro
      
    - set_fact: my_variable="{{ out_pro.stdout.split(' ')[0] }}" 
    - set_fact: my_varwithslash="{{ my_variable }}{{ add_slash }}"
    - set_fact: temp_path="{{ my_varwithslash + temp_dir|default(default_temp_dir) }}"
     
    
    - debug:
      #  msg: "{{ my_variable }}{{ add_slash }}"
        msg: "{{ temp_path }}"
      
  
    - name: Create temp directory on the local datastore to download esx update
      file:
      #  path: "{{ my_varwithslash + temp_dir|default(default_temp_dir) }}"
        path: "{{ temp_path }}"
        state: directory
        mode: 0755
      

