---
- hosts: all
  tasks:
  - include_vars: "update_esxi_defaults.yaml"
  
  - name: list profiles in bundle
    shell: "esxcli storage filesystem list | grep datastore"
    register: out_pro
    
  - debug:
      location: "{{ out_pro.stdout.split(' ')[0] }}"
  
    
 # - name: Create temp directory
 #     file:
 #       path: "{{ '/vmfs/volumes/datastore*/' + temp_dir|default(default_temp_dir) }}"
 #       state: directory
 #       mode: 0755
      

