---
- hosts: all
  vars:
    add_slash: "/"
    
  tasks: 
    - include_vars: "update_esxi_defaults.yaml"
  
    - name: list profiles in bundle
      shell: "esxcli storage filesystem list | grep datastore"
      register: out_pro
      
    - set_fact: my_variable="{{ out_pro.stdout.split(' ')[0] }}" + "{{ add_slash }}"
     
    
    - debug:
        msg: "{{ my_variable }}{{ add_slash }}"
      #  msg: "{{ my_variable }}"
      
  
    - name: Create temp directory
      file:
        path: "{{ {{ my_variable }}{{ add_slash }} + temp_dir|default(default_temp_dir) }}"
        state: directory
        mode: 0755
      

