---
- hosts: all
  vars:
    varaible: "None"
  tasks:
  - include_vars: "update_esxi_defaults.yaml"
  
  - name: list profiles in bundle
    shell: "esxcli storage filesystem list | grep datastore"
    register: out_pro
    variable: "{{ out_pro.stdout.split(' ')[0] }}"
    
  - debug:
      msg: "{{ out_pro.stdout.split(' ')[0] }}"
      
  
  - name: Create temp directory
    file:
      path: "{{ variable + temp_dir|default(default_temp_dir) }}"
      state: directory
      mode: 0755
      

